from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
)

# -------------------------------------------------------
# Styles
# -------------------------------------------------------

styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    fontSize=28,
    alignment=TA_CENTER,
    textColor=colors.HexColor("#0B5394"),
    spaceAfter=25,
)

SUBTITLE_STYLE = ParagraphStyle(
    "SubtitleStyle",
    parent=styles["Heading2"],
    alignment=TA_CENTER,
    textColor=colors.grey,
    spaceAfter=40,
)

HEADING_STYLE = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading1"],
    fontSize=18,
    textColor=colors.HexColor("#0B5394"),
    spaceBefore=15,
    spaceAfter=12,
)

BODY_STYLE = ParagraphStyle(
    "BodyStyle",
    parent=styles["BodyText"],
    fontSize=11,
    leading=18,
)

# -------------------------------------------------------
# Footer
# -------------------------------------------------------

def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()

    canvas.setFont("Helvetica", 9)

    canvas.drawString(
        inch,
        0.5 * inch,
        "Autonomous AI Data Scientist"
    )

    canvas.drawRightString(
        7.5 * inch,
        0.5 * inch,
        f"Page {page_num}"
    )

# -------------------------------------------------------
# PDF Generator
# -------------------------------------------------------

class PDFGenerator:

    @staticmethod
    def generate(report_data, output_path):

        doc = SimpleDocTemplate(output_path)

        elements = []

        dataset_name = report_data.get(
            "dataset_name",
            "Unknown Dataset"
        )

        dataset = report_data.get("dataset")

        # =====================================================
        # COVER PAGE
        # =====================================================

        elements.append(
            Paragraph(
                "Autonomous AI Data Scientist",
                TITLE_STYLE
            )
        )

        elements.append(
            Paragraph(
                "Machine Learning Analysis Report",
                SUBTITLE_STYLE
            )
        )

        elements.append(Spacer(1, 0.7 * inch))

        elements.append(
            Paragraph(
                f"<b>Dataset:</b> {dataset_name}",
                BODY_STYLE
            )
        )

        elements.append(
            Paragraph(
                f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %H:%M')}",
                BODY_STYLE
            )
        )

        elements.append(Spacer(1, 4 * inch))

        elements.append(
            Paragraph(
                "<b>Generated by AutoDS AI</b>",
                BODY_STYLE
            )
        )

        elements.append(PageBreak())

        # =====================================================
        # EXECUTIVE SUMMARY
        # =====================================================

        elements.append(
            Paragraph(
                "Executive Summary",
                HEADING_STYLE
            )
        )

        summary_data = [
            ["Metric", "Value"],
            ["Dataset", dataset_name],
            ["Generated", datetime.now().strftime("%d %B %Y")],
        ]

        if dataset is not None:
            summary_data.extend([
                ["Rows", dataset.shape[0]],
                ["Columns", dataset.shape[1]],
                ["Missing Values", int(dataset.isnull().sum().sum())],
                ["Duplicate Rows", int(dataset.duplicated().sum())],
                [
                    "Memory Usage (KB)",
                    round(dataset.memory_usage(deep=True).sum() / 1024, 2),
                ],
            ])

        automl = report_data.get("automl_results")

        if automl:
            best = automl["best_model"]
            metric = automl["metric"]

            summary_data.extend([
                ["Best Model", best["Model"]],
                ["Evaluation Metric", metric],
                ["Best Score", round(best[metric], 4)],
            ])

        summary_table = Table(
            summary_data,
            colWidths=[200, 240]
        )

        summary_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B5394")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ])
        )

        elements.append(summary_table)
        elements.append(PageBreak())

        # =====================================================
        # DATASET OVERVIEW
        # =====================================================

        if dataset is not None:

            elements.append(
                Paragraph(
                    "Dataset Overview",
                    HEADING_STYLE
                )
            )

            table_data = [
                ["Metric", "Value"],
                ["Dataset", dataset_name],
                ["Rows", dataset.shape[0]],
                ["Columns", dataset.shape[1]],
                ["Missing Values", dataset.isnull().sum().sum()],
                ["Duplicate Rows", dataset.duplicated().sum()],
                ["Memory Usage (KB)",
                 round(dataset.memory_usage(deep=True).sum()/1024, 2)]
            ]

            table = Table(
                table_data,
                colWidths=[220, 220]
            )

            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B5394")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER")
            ]))

            elements.append(table)
            elements.append(Spacer(1, 20))

        # =====================================================
        # DATASET VISUALIZATIONS
        # =====================================================

        charts = report_data.get("charts", [])

        if charts:
            elements.append(PageBreak())
            elements.append(
                Paragraph(
                    "Dataset Visualizations",
                    HEADING_STYLE
                )
            )

            for chart in charts:
                elements.append(
                    Image(
                        chart,
                        width=5.8 * inch,
                        height=3.2 * inch
                    )
                )
                elements.append(Spacer(1, 12))

        # =====================================================
        # MODEL COMPARISON
        # =====================================================
        if automl:
            elements.append(PageBreak())
            elements.append(
                Paragraph(
                    "Model Comparison",
                    HEADING_STYLE
                )
            )
            leaderboard = automl.get("leaderboard", [])
            metric = automl.get("metric")
            table_data = [
                ["Rank", "Model", metric]
            ]
            medals = ["🥇", "🥈", "🥉"]
            for index, model in enumerate(leaderboard):
                rank = medals[index] if index < 3 else str(index + 1)
                score = round(model[metric], 4)
                table_data.append([
                    rank,
                    model["Model"],
                    score
                ])
            comparison_table = Table(
                table_data,
                colWidths=[60, 250, 100]
            )
            comparison_table.setStyle(
                TableStyle([
                    ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0B5394")),
                    ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                    ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
                    ("GRID",(0,0),(-1,-1),0.5,colors.grey),
                    ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),
                    ("ALIGN",(0,0),(-1,-1),"CENTER"),
                    ("BOTTOMPADDING",(0,0),(-1,0),8)
                ])
            )
            elements.append(comparison_table)
            elements.append(Spacer(1,20))

        # =====================================================
        # BEST MODEL
        # =====================================================

        if automl:
            elements.append(PageBreak())
            elements.append(
                Paragraph(
                    "Best Model",
                    HEADING_STYLE
                )
            )

            best = automl["best_model"]
            metric = automl["metric"]

            elements.append(
                Paragraph(
                    f"<b>Model:</b> {best['Model']}",
                    BODY_STYLE
                )
            )

            elements.append(
                Paragraph(
                    f"<b>{metric}:</b> {round(best[metric],4)}",
                    BODY_STYLE
                )
            )

            elements.append(Spacer(1, 20))

        # =====================================================
        # EXPLAINABILITY
        # =====================================================

        if report_data.get("shap_results"):
            elements.append(
                Paragraph(
                    "Explainability",
                    HEADING_STYLE
                )
            )

            elements.append(
                Paragraph(
                    "SHAP feature importance analysis completed successfully.",
                    BODY_STYLE
                )
            )

            elements.append(Spacer(1, 20))

        # =====================================================
        # CONCLUSION
        # =====================================================

        elements.append(PageBreak())

        elements.append(
            Paragraph(
                "Conclusion",
                HEADING_STYLE
            )
        )

        elements.append(
            Paragraph(
                "The dataset was successfully analyzed, machine learning models were evaluated, "
                "and the best-performing model was identified. "
                "This report was automatically generated by the Autonomous AI Data Scientist platform.",
                BODY_STYLE
            )
        )

        # =====================================================
        # BUILD PDF
        # =====================================================

        doc.build(
            elements,
            onFirstPage=add_page_number,
            onLaterPages=add_page_number
        )

        return output_path